export const StatesDataFields = {
    EscrPC: "EscrPC",
    EscrPCCond: "EscrPCCond",
    IoD: "IoD",
    LeerMem: "LeerMem",
    EscrMem: "EscrMem",
    EsrcIR: "EsrcIR",
    MemaReg: "MemaReg",
    FuentePC1: "FuentePC1",
    FuentePC0: "FuentePC0",
    ALUOp1: "AlUOp1",
    ALUOp0: "AlUOp0",
    SelALUB1: "SelALUB1",
    SelALUB0: "SelALUB0",
    SelALUA: "SelALUA",
    EscrReg: "EscrReg",
    RegDest: "RegDest",
}